---
- include: load_variable.yml

- name: Install required system packages
  become: true
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['python3-pip', 'virtualenv', 'python3-setuptools', 'python-setuptools']

- name: Install docker packages
  remote_user: ubuntu
  apt:
    name: "{{ docker_prerequisite_packages }}"
    state: present
  tags:
    - docker

- name: Add Docker official GPG key
  remote_user: ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Verify that we have the key with the fingerprint
  remote_user: ubuntu
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker

- name: Set up the stable repository
  remote_user: ubuntu
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  tags:
    - docker

- name: Update apt packages
  remote_user: ubuntu
  apt:
    update_cache: yes
  tags:
    - docker

- name: Install docker
  remote_user: ubuntu
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: ['docker-ce', 'docker-compose', 'python-docker']
  tags:
    - docker

- name: Add remote "ubuntu" user to "docker" group
  remote_user: ubuntu
  user:
    name: "ubuntu"
    group: "docker"
    append: yes
  tags:
    - docker





